### ISSUE TITLE
checkForExisting sets loading only once

### ISSUE THREAD

**Issue by edemaine** [hupe1980/react-script-hook#27]
I'm considering using this hook in a multitab application, where each tab may want to load a (possibly identical) script before doing some computation.  If I'm reading this effect correctly:

https://github.com/hupe1980/react-script-hook/blob/9f720a49169ee50dd68b5bb46c2e7d26df7ca98d/src/use-script.tsx#L22-L28

If the `<script>` already exists, then `loading` will get set *once* to the current state, but `loading` won't ever resolve to `false` (even after the script loads).  Also, this code ignores the `'error'` state.

I see two possible fixes:
1. Add additional `load` and `error` handlers when `existing.getAttribute('data-status') === 'loading'`.  And check for `existing.getAttribute('data-status') === 'error'`.
2. Keep a global map from script `src`s to an array of `{setLoading, setError}` callbacks, so that when the original `load` and `error` handlers get called, all the relevant states get set. The advantages of this approach:
   * You wouldn't need `data-status` attribute anymore, as it's tracked in the global data structure.
   * #24 would get resolved in the sense that we could immediately detect scripts that had already been added, instead of having to use DOM manipulation.

Approach 2 seems more powerful but a bit more complicated. Which would you prefer? I can try to put together a PR either way.

**Comment by hupe1980** [comment]
If variant 2 is also a solution for #24, I would prefer this. You are welcome to create a PR
